tap 'homebrew/dupes'

brew 'coreutils'
brew 'openssl'
brew 'wget'
brew 'redis'
brew 'postgresql'
brew 'imagemagick'
brew 'grc'


# Install Cask
brew 'caskroom/cask/brew-cask'
tap 'caskroom/homebrew-versions'
# tap 'caskroom/versions'

# Install Casks
cask 'dropbox'
cask 'github'
cask 'google-chrome'
cask 'slack'
cask 'coconutbattery'
cask 'transmission'
cask 'the-unarchiver'
cask 'vlc'
