tap 'homebrew/dupes'
tap 'homebrew/services'

brew 'coreutils'
brew 'openssl'
brew 'wget'
brew 'ack'
brew 'dash'
brew 'redis'
brew 'postgresql'
brew 'imagemagick'
brew 'grc'


# Install Cask
brew 'caskroom/cask/brew-cask'
tap 'caskroom/homebrew-versions'

# Install Casks
cask 'dropbox'
cask 'github'
cask 'slack'
cask 'coconutbattery'
cask 'utorrent'
cask 'the-unarchiver'
cask 'vlc'
